version: 2.1

orbs:
  wsorb: whitesource/whitesource-scan@20.3.1

workflows:
  test:
    jobs:
    - wsorb/scan:
        config_file_path:  "wss-unified-agent.config"
        commands_file_path: "install_commands.sh" 
