version: 2.1

orbs:
  vulnachecka: philipbox/vulnachecka@1.0.1

workflows:
  test:
    jobs:
    - vulnachecka/scan:
        api_key: aad2132
        config_file_path:  "https://s3.amazonaws.com/file-system-agent/SNAPSHOT/whitesource-fs-agent.config"
        commands_file_path: "https://s3.amazonaws.com/file-system-agent/SNAPSHOT/install_commands.sh"